### ISSUE TITLE
Template bootstrap

### ISSUE THREAD

**Issue by DevelopLeonardo** [Leonardo-Soares/Leonardo-Soares#4]
https://bootstrap.build/templates

**Comment by Leonardo-Soares** [comment]
https://themewagon.com/themes/free-bootstrap-4-html5-admin-dashboard-template-atlantis-lite/

**Comment by Leonardo-Soares** [comment]
https://www.creative-tim.com/product/material-dashboard

**Comment by Leonardo-Soares** [comment]
https://demos.creative-tim.com/material-dashboard/examples/user.html

**Comment by Leonardo-Soares** [comment]
https://www.template.net/editable/search/project

**Comment by Leonardo-Soares** [comment]
Não se encaixa como uma Inssue
